#!/bin/bash
# Demonstration script for MTD packet transfer with visible acknowledgments

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║       MTD Packet Transfer Demo - With Acknowledgments               ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "This script demonstrates actual packet transfer between hosts with"
echo "visible acknowledgments showing the complete communication flow."
echo ""
echo "Prerequisites:"
echo "  1. Controller must be running (Terminal 1)"
echo "  2. Mininet must be running (Terminal 2)"
echo ""
read -p "Press Enter to continue..."

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 1: Direct Host-to-Host Communication"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This test sends packets directly between h1 and h2 using host agents."
echo "You will see:"
echo "  - Packet being sent from h1"
echo "  - Packet being received by h2"
echo "  - Acknowledgment being sent back"
echo ""
echo "Commands to run in Mininet CLI:"
echo ""
echo "  # Check h2's log to see packets arriving:"
echo "  mininet> h2 tail -f /tmp/h2_agent.log &"
echo ""
echo "  # Send a test packet from h1 to h2:"
echo "  mininet> h1 python3 scripts/host_agent.py --host h1 --client --target h2 --count 1"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 2: Controller-Orchestrated Transfer"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This test uses the controller's API to orchestrate packet transfer."
echo "You will see:"
echo "  - Policy check (zone-based access control)"
echo "  - Network connectivity verification"
echo "  - Encryption layer applied"
echo "  - NAT translation"
echo "  - Packet transfer"
echo "  - Acknowledgment confirmation"
echo ""
echo "Command to run in a new terminal:"
echo ""
echo '  curl -X POST http://127.0.0.1:8000/sim/secure_transfer \'
echo '    -H "Content-Type: application/json" \'
echo '    -d '"'"'{"src":"h1","dst":"h2","payload":"Hello from h1 to h2!"}'"'"' \'
echo '    | jq'
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 3: Continuous Packet Stream"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This test demonstrates continuous packet transfer with MTD IP rotation."
echo ""
echo "In Terminal 3 - Monitor h2 receiving packets:"
echo "  tail -f /tmp/h2_agent.log"
echo ""
echo "In Mininet CLI - Send continuous stream:"
echo "  mininet> h1 python3 scripts/host_agent.py --host h1 --client --target h2 --count 10 --interval 3"
echo ""
echo "In Terminal 4 - Trigger MTD rotation during transfer:"
echo "  curl -X POST http://127.0.0.1:8000/shuffle -d '{\"hosts\":[\"h1\",\"h2\"]}'"
echo ""
echo "You should observe:"
echo "  - Packets continuously being sent and acknowledged"
echo "  - IP addresses changing (MTD rotation)"
echo "  - Communication continuing despite IP changes"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Test 4: View Real-Time Logs"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Monitor host agent logs to see actual packet transfers:"
echo ""
echo "  # h1 (sender) logs:"
echo "  tail -f /tmp/h1_agent.log"
echo ""
echo "  # h2 (receiver) logs:"
echo "  tail -f /tmp/h2_agent.log"
echo ""
echo "  # All hosts:"
echo "  tail -f /tmp/h*_agent.log"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Expected Output Format"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "On h1 (sender):"
echo "  ======================================================================"
echo "  [12:34:56] [h1] INFO: 📤 SENDING PACKET"
echo "  [12:34:56] [h1] INFO:    To: h2 (172.16.0.198:8080)"
echo "  [12:34:56] [h1] INFO:    Message ID: #1"
echo "  [12:34:56] [h1] INFO:    Payload: Test message #1 from h1 to h2..."
echo "  ======================================================================"
echo "  ======================================================================"
echo "  [12:34:56] [h1] SUCCESS: ✅ ACKNOWLEDGMENT RECEIVED"
echo "  [12:34:56] [h1] SUCCESS:    From: h2 (172.16.0.198)"
echo "  [12:34:56] [h1] SUCCESS:    Status: ACK"
echo "  [12:34:56] [h1] SUCCESS:    Message: Packet received and acknowledged"
echo "  [12:34:56] [h1] SUCCESS:    Bytes delivered: 234"
echo "  ======================================================================"
echo ""
echo "On h2 (receiver):"
echo "  ======================================================================"
echo "  [12:34:56] [h2] SUCCESS: 📥 PACKET RECEIVED"
echo "  [12:34:56] [h2] SUCCESS:    From: h1 (172.16.0.21)"
echo "  [12:34:56] [h2] SUCCESS:    Size: 234 bytes"
echo "  [12:34:56] [h2] SUCCESS:    Data: Test message #1 from h1 to h2..."
echo "  ======================================================================"
echo "  [12:34:56] [h2] INFO: ✅ ACK sent to h1"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Tips:"
echo "  - Use multiple terminals to see sender and receiver simultaneously"
echo "  - Watch for IP changes during MTD shuffles"
echo "  - Check /tmp/h*_agent.log files for complete history"
echo "  - Use 'jq' to format JSON output from controller API"
echo ""
echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║                    Ready to demonstrate!                             ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
